package com.henrrycheng.chyftt.intermediary.experienceInteraction.bo;

import com.baidu.bjf.dao.ColumnDescription;
import com.baidu.bjf.dao.FieldAccessVo;
import com.baidu.bjf.dao.Id;
import java.io.Serializable;
import java.util.Collections;
import java.util.Date;
import java.util.Map;
import java.util.WeakHashMap;
import org.apache.commons.lang.ObjectUtils;

/**
 * This bo is map to table : tb_experience_interaction
 * Table description : 事情经过互动记录
 * @author chengyong
 */
public abstract class ExperienceInteractionBase extends FieldAccessVo implements Serializable {
    /** serial Version UID. */
    private static final long serialVersionUID = -1L;

    /** hashCode temporary storage. */
    private volatile Long hashCode;

    /** Use a WeakHashMap so entries will be garbage collected once all entities 
    referring to a saved hash are garbage collected themselves. */
    private static final Map<Serializable, Long> SAVED_HASHES = 
        Collections.synchronizedMap(new WeakHashMap<Serializable, Long>());

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_experience_interaction.id
     *
     * @mbggenerated Sat Mar 18 22:56:42 CST 2017
     */
    @ColumnDescription(desc = "id")
    @Id
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_experience_interaction.experience_id
     *
     * @mbggenerated Sat Mar 18 22:56:42 CST 2017
     */
    @ColumnDescription(desc = "事情经过id")
    private Long experienceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_experience_interaction.type
     *
     * @mbggenerated Sat Mar 18 22:56:42 CST 2017
     */
    @ColumnDescription(desc = "操作类型：1 浏览, 10 顶，-10 踩，20：评论")
    private Long type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_experience_interaction.value
     *
     * @mbggenerated Sat Mar 18 22:56:42 CST 2017
     */
    @ColumnDescription(desc = "操作权值")
    private Long value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_experience_interaction.ip_addr
     *
     * @mbggenerated Sat Mar 18 22:56:42 CST 2017
     */
    @ColumnDescription(desc = "ip地址")
    private String ipAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_experience_interaction.add_time
     *
     * @mbggenerated Sat Mar 18 22:56:42 CST 2017
     */
    @ColumnDescription(desc = "添加时间")
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_experience_interaction.add_user_id
     *
     * @mbggenerated Sat Mar 18 22:56:42 CST 2017
     */
    @ColumnDescription(desc = "添加人id")
    private Long addUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_experience_interaction.update_time
     *
     * @mbggenerated Sat Mar 18 22:56:42 CST 2017
     */
    @ColumnDescription(desc = "更新时间")
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_experience_interaction.update_user_id
     *
     * @mbggenerated Sat Mar 18 22:56:42 CST 2017
     */
    @ColumnDescription(desc = "更新人id")
    private Long updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_experience_interaction.is_active
     *
     * @mbggenerated Sat Mar 18 22:56:42 CST 2017
     */
    @ColumnDescription(desc = "是否有效，1有效，0无效")
    private Boolean isActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_experience_interaction.is_deleted
     *
     * @mbggenerated Sat Mar 18 22:56:42 CST 2017
     */
    @ColumnDescription(desc = "是否已逻辑删除，0未删除，1已删除")
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_experience_interaction.id
     *
     * @return the value of tb_experience_interaction.id
     *
     * @mbggenerated Sat Mar 18 22:56:42 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_experience_interaction.id
     *
     * @param id the value for tb_experience_interaction.id
     *
     * @mbggenerated Sat Mar 18 22:56:42 CST 2017
     */
    public void setId(Long id) {
        // If we've just been persisted and hashCode has been
        // returned then make sure other entities with this
        // ID return the already returned hash code
        if ( this.id == null && id != null && this.hashCode != null ) {
            SAVED_HASHES.put( id, this.hashCode );
        }
        if (!ObjectUtils.equals(id, this.id)) {
            getChangeLogInfo().put("id", id);
        }
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_experience_interaction.experience_id
     *
     * @return the value of tb_experience_interaction.experience_id
     *
     * @mbggenerated Sat Mar 18 22:56:42 CST 2017
     */
    public Long getExperienceId() {
        return experienceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_experience_interaction.experience_id
     *
     * @param experienceId the value for tb_experience_interaction.experience_id
     *
     * @mbggenerated Sat Mar 18 22:56:42 CST 2017
     */
    public void setExperienceId(Long experienceId) {
        if (!ObjectUtils.equals(experienceId, this.experienceId)) {
            getChangeLogInfo().put("experienceId", experienceId);
        }
        this.experienceId = experienceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_experience_interaction.type
     *
     * @return the value of tb_experience_interaction.type
     *
     * @mbggenerated Sat Mar 18 22:56:42 CST 2017
     */
    public Long getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_experience_interaction.type
     *
     * @param type the value for tb_experience_interaction.type
     *
     * @mbggenerated Sat Mar 18 22:56:42 CST 2017
     */
    public void setType(Long type) {
        if (!ObjectUtils.equals(type, this.type)) {
            getChangeLogInfo().put("type", type);
        }
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_experience_interaction.value
     *
     * @return the value of tb_experience_interaction.value
     *
     * @mbggenerated Sat Mar 18 22:56:42 CST 2017
     */
    public Long getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_experience_interaction.value
     *
     * @param value the value for tb_experience_interaction.value
     *
     * @mbggenerated Sat Mar 18 22:56:42 CST 2017
     */
    public void setValue(Long value) {
        if (!ObjectUtils.equals(value, this.value)) {
            getChangeLogInfo().put("value", value);
        }
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_experience_interaction.ip_addr
     *
     * @return the value of tb_experience_interaction.ip_addr
     *
     * @mbggenerated Sat Mar 18 22:56:42 CST 2017
     */
    public String getIpAddr() {
        return ipAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_experience_interaction.ip_addr
     *
     * @param ipAddr the value for tb_experience_interaction.ip_addr
     *
     * @mbggenerated Sat Mar 18 22:56:42 CST 2017
     */
    public void setIpAddr(String ipAddr) {
        if (!ObjectUtils.equals(ipAddr, this.ipAddr)) {
            getChangeLogInfo().put("ipAddr", ipAddr);
        }
        this.ipAddr = ipAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_experience_interaction.add_time
     *
     * @return the value of tb_experience_interaction.add_time
     *
     * @mbggenerated Sat Mar 18 22:56:42 CST 2017
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_experience_interaction.add_time
     *
     * @param addTime the value for tb_experience_interaction.add_time
     *
     * @mbggenerated Sat Mar 18 22:56:42 CST 2017
     */
    public void setAddTime(Date addTime) {
        if (!ObjectUtils.equals(addTime, this.addTime)) {
            getChangeLogInfo().put("addTime", addTime);
        }
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_experience_interaction.add_user_id
     *
     * @return the value of tb_experience_interaction.add_user_id
     *
     * @mbggenerated Sat Mar 18 22:56:42 CST 2017
     */
    public Long getAddUserId() {
        return addUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_experience_interaction.add_user_id
     *
     * @param addUserId the value for tb_experience_interaction.add_user_id
     *
     * @mbggenerated Sat Mar 18 22:56:42 CST 2017
     */
    public void setAddUserId(Long addUserId) {
        if (!ObjectUtils.equals(addUserId, this.addUserId)) {
            getChangeLogInfo().put("addUserId", addUserId);
        }
        this.addUserId = addUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_experience_interaction.update_time
     *
     * @return the value of tb_experience_interaction.update_time
     *
     * @mbggenerated Sat Mar 18 22:56:42 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_experience_interaction.update_time
     *
     * @param updateTime the value for tb_experience_interaction.update_time
     *
     * @mbggenerated Sat Mar 18 22:56:42 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        if (!ObjectUtils.equals(updateTime, this.updateTime)) {
            getChangeLogInfo().put("updateTime", updateTime);
        }
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_experience_interaction.update_user_id
     *
     * @return the value of tb_experience_interaction.update_user_id
     *
     * @mbggenerated Sat Mar 18 22:56:42 CST 2017
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_experience_interaction.update_user_id
     *
     * @param updateUserId the value for tb_experience_interaction.update_user_id
     *
     * @mbggenerated Sat Mar 18 22:56:42 CST 2017
     */
    public void setUpdateUserId(Long updateUserId) {
        if (!ObjectUtils.equals(updateUserId, this.updateUserId)) {
            getChangeLogInfo().put("updateUserId", updateUserId);
        }
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_experience_interaction.is_active
     *
     * @return the value of tb_experience_interaction.is_active
     *
     * @mbggenerated Sat Mar 18 22:56:42 CST 2017
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_experience_interaction.is_active
     *
     * @param isActive the value for tb_experience_interaction.is_active
     *
     * @mbggenerated Sat Mar 18 22:56:42 CST 2017
     */
    public void setIsActive(Boolean isActive) {
        if (!ObjectUtils.equals(isActive, this.isActive)) {
            getChangeLogInfo().put("isActive", isActive);
        }
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_experience_interaction.is_deleted
     *
     * @return the value of tb_experience_interaction.is_deleted
     *
     * @mbggenerated Sat Mar 18 22:56:42 CST 2017
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_experience_interaction.is_deleted
     *
     * @param isDeleted the value for tb_experience_interaction.is_deleted
     *
     * @mbggenerated Sat Mar 18 22:56:42 CST 2017
     */
    public void setIsDeleted(Boolean isDeleted) {
        if (!ObjectUtils.equals(isDeleted, this.isDeleted)) {
            getChangeLogInfo().put("isDeleted", isDeleted);
        }
        this.isDeleted = isDeleted;
    }

    @Override
    public int hashCode() {
        if ( this.hashCode == null ) {
            synchronized ( this ) {
                if ( this.hashCode == null ) {
                    Long newHashCode = null;
                    if ( getId() != null ) {
                        newHashCode = SAVED_HASHES.get( getId() );
                    }
                    
                    if ( newHashCode == null ) {
                        if ( getId() != null ) {
                            newHashCode = (long)getId().hashCode();
                        } else {
                            newHashCode = (long) super.hashCode();
                        }
                    }
                    this.hashCode = newHashCode;
                }
            }
        }
        return (int) (this.hashCode & 0xffffff);
    }

    @Override
    public boolean equals(final Object aThat) {
        
        if ( this == aThat ) {
            return true;
        }
        if( aThat == null ) {
            return false;
        }
        if (!( aThat instanceof ExperienceInteractionBase )) {
            return false;
        }
        
        final ExperienceInteractionBase THAT = (ExperienceInteractionBase) aThat;
        boolean result = true;
        result = result && (((this.getId() == null) &&
             ( THAT.getId() == null)) || (this.getId() != null  && 
            this.getId().equals(THAT.getId())));
        return result;
    }
}