package com.henrrycheng.chyftt.intermediary.cityCompanyCommunityRelation.bo;

import com.baidu.bjf.dao.ColumnDescription;
import com.baidu.bjf.dao.FieldAccessVo;
import com.baidu.bjf.dao.Id;
import java.io.Serializable;
import java.util.Collections;
import java.util.Date;
import java.util.Map;
import java.util.WeakHashMap;
import org.apache.commons.lang.ObjectUtils;

/**
 * This bo is map to table : tb_relation_city_company_community
 * Table description : 城市-公司-小区关系表
 * @author chengyong
 */
public abstract class RelationCityCompanyCommunityBase extends FieldAccessVo implements Serializable {
    /** serial Version UID. */
    private static final long serialVersionUID = -1L;

    /** hashCode temporary storage. */
    private volatile Long hashCode;

    /** Use a WeakHashMap so entries will be garbage collected once all entities 
    referring to a saved hash are garbage collected themselves. */
    private static final Map<Serializable, Long> SAVED_HASHES = 
        Collections.synchronizedMap(new WeakHashMap<Serializable, Long>());

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_relation_city_company_community.id
     *
     * @mbggenerated Sat Mar 18 22:52:32 CST 2017
     */
    @ColumnDescription(desc = "id")
    @Id
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_relation_city_company_community.city_id
     *
     * @mbggenerated Sat Mar 18 22:52:32 CST 2017
     */
    @ColumnDescription(desc = "城市id")
    private Long cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_relation_city_company_community.company_id
     *
     * @mbggenerated Sat Mar 18 22:52:32 CST 2017
     */
    @ColumnDescription(desc = "公司id")
    private Long companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_relation_city_company_community.community_id
     *
     * @mbggenerated Sat Mar 18 22:52:32 CST 2017
     */
    @ColumnDescription(desc = "小区id")
    private Long communityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_relation_city_company_community.add_time
     *
     * @mbggenerated Sat Mar 18 22:52:32 CST 2017
     */
    @ColumnDescription(desc = "添加时间")
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_relation_city_company_community.add_user_id
     *
     * @mbggenerated Sat Mar 18 22:52:32 CST 2017
     */
    @ColumnDescription(desc = "添加人id")
    private Long addUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_relation_city_company_community.update_time
     *
     * @mbggenerated Sat Mar 18 22:52:32 CST 2017
     */
    @ColumnDescription(desc = "更新时间")
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_relation_city_company_community.update_user_id
     *
     * @mbggenerated Sat Mar 18 22:52:32 CST 2017
     */
    @ColumnDescription(desc = "更新人id")
    private Long updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_relation_city_company_community.is_deleted
     *
     * @mbggenerated Sat Mar 18 22:52:32 CST 2017
     */
    @ColumnDescription(desc = "是否已逻辑删除，0未删除，1已删除")
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_relation_city_company_community.id
     *
     * @return the value of tb_relation_city_company_community.id
     *
     * @mbggenerated Sat Mar 18 22:52:32 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_relation_city_company_community.id
     *
     * @param id the value for tb_relation_city_company_community.id
     *
     * @mbggenerated Sat Mar 18 22:52:32 CST 2017
     */
    public void setId(Long id) {
        // If we've just been persisted and hashCode has been
        // returned then make sure other entities with this
        // ID return the already returned hash code
        if ( this.id == null && id != null && this.hashCode != null ) {
            SAVED_HASHES.put( id, this.hashCode );
        }
        if (!ObjectUtils.equals(id, this.id)) {
            getChangeLogInfo().put("id", id);
        }
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_relation_city_company_community.city_id
     *
     * @return the value of tb_relation_city_company_community.city_id
     *
     * @mbggenerated Sat Mar 18 22:52:32 CST 2017
     */
    public Long getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_relation_city_company_community.city_id
     *
     * @param cityId the value for tb_relation_city_company_community.city_id
     *
     * @mbggenerated Sat Mar 18 22:52:32 CST 2017
     */
    public void setCityId(Long cityId) {
        if (!ObjectUtils.equals(cityId, this.cityId)) {
            getChangeLogInfo().put("cityId", cityId);
        }
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_relation_city_company_community.company_id
     *
     * @return the value of tb_relation_city_company_community.company_id
     *
     * @mbggenerated Sat Mar 18 22:52:32 CST 2017
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_relation_city_company_community.company_id
     *
     * @param companyId the value for tb_relation_city_company_community.company_id
     *
     * @mbggenerated Sat Mar 18 22:52:32 CST 2017
     */
    public void setCompanyId(Long companyId) {
        if (!ObjectUtils.equals(companyId, this.companyId)) {
            getChangeLogInfo().put("companyId", companyId);
        }
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_relation_city_company_community.community_id
     *
     * @return the value of tb_relation_city_company_community.community_id
     *
     * @mbggenerated Sat Mar 18 22:52:32 CST 2017
     */
    public Long getCommunityId() {
        return communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_relation_city_company_community.community_id
     *
     * @param communityId the value for tb_relation_city_company_community.community_id
     *
     * @mbggenerated Sat Mar 18 22:52:32 CST 2017
     */
    public void setCommunityId(Long communityId) {
        if (!ObjectUtils.equals(communityId, this.communityId)) {
            getChangeLogInfo().put("communityId", communityId);
        }
        this.communityId = communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_relation_city_company_community.add_time
     *
     * @return the value of tb_relation_city_company_community.add_time
     *
     * @mbggenerated Sat Mar 18 22:52:32 CST 2017
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_relation_city_company_community.add_time
     *
     * @param addTime the value for tb_relation_city_company_community.add_time
     *
     * @mbggenerated Sat Mar 18 22:52:32 CST 2017
     */
    public void setAddTime(Date addTime) {
        if (!ObjectUtils.equals(addTime, this.addTime)) {
            getChangeLogInfo().put("addTime", addTime);
        }
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_relation_city_company_community.add_user_id
     *
     * @return the value of tb_relation_city_company_community.add_user_id
     *
     * @mbggenerated Sat Mar 18 22:52:32 CST 2017
     */
    public Long getAddUserId() {
        return addUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_relation_city_company_community.add_user_id
     *
     * @param addUserId the value for tb_relation_city_company_community.add_user_id
     *
     * @mbggenerated Sat Mar 18 22:52:32 CST 2017
     */
    public void setAddUserId(Long addUserId) {
        if (!ObjectUtils.equals(addUserId, this.addUserId)) {
            getChangeLogInfo().put("addUserId", addUserId);
        }
        this.addUserId = addUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_relation_city_company_community.update_time
     *
     * @return the value of tb_relation_city_company_community.update_time
     *
     * @mbggenerated Sat Mar 18 22:52:32 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_relation_city_company_community.update_time
     *
     * @param updateTime the value for tb_relation_city_company_community.update_time
     *
     * @mbggenerated Sat Mar 18 22:52:32 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        if (!ObjectUtils.equals(updateTime, this.updateTime)) {
            getChangeLogInfo().put("updateTime", updateTime);
        }
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_relation_city_company_community.update_user_id
     *
     * @return the value of tb_relation_city_company_community.update_user_id
     *
     * @mbggenerated Sat Mar 18 22:52:32 CST 2017
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_relation_city_company_community.update_user_id
     *
     * @param updateUserId the value for tb_relation_city_company_community.update_user_id
     *
     * @mbggenerated Sat Mar 18 22:52:32 CST 2017
     */
    public void setUpdateUserId(Long updateUserId) {
        if (!ObjectUtils.equals(updateUserId, this.updateUserId)) {
            getChangeLogInfo().put("updateUserId", updateUserId);
        }
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_relation_city_company_community.is_deleted
     *
     * @return the value of tb_relation_city_company_community.is_deleted
     *
     * @mbggenerated Sat Mar 18 22:52:32 CST 2017
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_relation_city_company_community.is_deleted
     *
     * @param isDeleted the value for tb_relation_city_company_community.is_deleted
     *
     * @mbggenerated Sat Mar 18 22:52:32 CST 2017
     */
    public void setIsDeleted(Boolean isDeleted) {
        if (!ObjectUtils.equals(isDeleted, this.isDeleted)) {
            getChangeLogInfo().put("isDeleted", isDeleted);
        }
        this.isDeleted = isDeleted;
    }

    @Override
    public int hashCode() {
        if ( this.hashCode == null ) {
            synchronized ( this ) {
                if ( this.hashCode == null ) {
                    Long newHashCode = null;
                    if ( getId() != null ) {
                        newHashCode = SAVED_HASHES.get( getId() );
                    }
                    
                    if ( newHashCode == null ) {
                        if ( getId() != null ) {
                            newHashCode = (long)getId().hashCode();
                        } else {
                            newHashCode = (long) super.hashCode();
                        }
                    }
                    this.hashCode = newHashCode;
                }
            }
        }
        return (int) (this.hashCode & 0xffffff);
    }

    @Override
    public boolean equals(final Object aThat) {
        
        if ( this == aThat ) {
            return true;
        }
        if( aThat == null ) {
            return false;
        }
        if (!( aThat instanceof RelationCityCompanyCommunityBase )) {
            return false;
        }
        
        final RelationCityCompanyCommunityBase THAT = (RelationCityCompanyCommunityBase) aThat;
        boolean result = true;
        result = result && (((this.getId() == null) &&
             ( THAT.getId() == null)) || (this.getId() != null  && 
            this.getId().equals(THAT.getId())));
        return result;
    }
}