package com.henrrycheng.chyftt.intermediary.community.bo;

import com.baidu.bjf.dao.ColumnDescription;
import com.baidu.bjf.dao.FieldAccessVo;
import com.baidu.bjf.dao.Id;
import java.io.Serializable;
import java.util.Collections;
import java.util.Date;
import java.util.Map;
import java.util.WeakHashMap;
import org.apache.commons.lang.ObjectUtils;

/**
 * This bo is map to table : td_community
 * Table description : 小区
 * @author chengyong
 */
public abstract class CommunityBase extends FieldAccessVo implements Serializable {
    /** serial Version UID. */
    private static final long serialVersionUID = -1L;

    /** hashCode temporary storage. */
    private volatile Long hashCode;

    /** Use a WeakHashMap so entries will be garbage collected once all entities 
    referring to a saved hash are garbage collected themselves. */
    private static final Map<Serializable, Long> SAVED_HASHES = 
        Collections.synchronizedMap(new WeakHashMap<Serializable, Long>());

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_community.id
     *
     * @mbggenerated Sat Mar 18 22:40:35 CST 2017
     */
    @ColumnDescription(desc = "id")
    @Id
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_community.name
     *
     * @mbggenerated Sat Mar 18 22:40:35 CST 2017
     */
    @ColumnDescription(desc = "小区名称")
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_community.type
     *
     * @mbggenerated Sat Mar 18 22:40:35 CST 2017
     */
    @ColumnDescription(desc = "小区类型：10 正常小区，20 回迁房")
    private Long type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_community.location
     *
     * @mbggenerated Sat Mar 18 22:40:35 CST 2017
     */
    @ColumnDescription(desc = "小区位置")
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_community.description
     *
     * @mbggenerated Sat Mar 18 22:40:35 CST 2017
     */
    @ColumnDescription(desc = "小区介绍")
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_community.description_source
     *
     * @mbggenerated Sat Mar 18 22:40:35 CST 2017
     */
    @ColumnDescription(desc = "小区介绍-资料来源")
    private String descriptionSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_community.add_time
     *
     * @mbggenerated Sat Mar 18 22:40:35 CST 2017
     */
    @ColumnDescription(desc = "添加时间")
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_community.add_user_id
     *
     * @mbggenerated Sat Mar 18 22:40:35 CST 2017
     */
    @ColumnDescription(desc = "添加人id")
    private Long addUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_community.update_time
     *
     * @mbggenerated Sat Mar 18 22:40:35 CST 2017
     */
    @ColumnDescription(desc = "更新时间")
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_community.update_user_id
     *
     * @mbggenerated Sat Mar 18 22:40:35 CST 2017
     */
    @ColumnDescription(desc = "更新人id")
    private Long updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_community.is_deleted
     *
     * @mbggenerated Sat Mar 18 22:40:35 CST 2017
     */
    @ColumnDescription(desc = "是否已逻辑删除，0未删除，1已删除")
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_community.id
     *
     * @return the value of td_community.id
     *
     * @mbggenerated Sat Mar 18 22:40:35 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_community.id
     *
     * @param id the value for td_community.id
     *
     * @mbggenerated Sat Mar 18 22:40:35 CST 2017
     */
    public void setId(Long id) {
        // If we've just been persisted and hashCode has been
        // returned then make sure other entities with this
        // ID return the already returned hash code
        if ( this.id == null && id != null && this.hashCode != null ) {
            SAVED_HASHES.put( id, this.hashCode );
        }
        if (!ObjectUtils.equals(id, this.id)) {
            getChangeLogInfo().put("id", id);
        }
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_community.name
     *
     * @return the value of td_community.name
     *
     * @mbggenerated Sat Mar 18 22:40:35 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_community.name
     *
     * @param name the value for td_community.name
     *
     * @mbggenerated Sat Mar 18 22:40:35 CST 2017
     */
    public void setName(String name) {
        if (!ObjectUtils.equals(name, this.name)) {
            getChangeLogInfo().put("name", name);
        }
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_community.type
     *
     * @return the value of td_community.type
     *
     * @mbggenerated Sat Mar 18 22:40:35 CST 2017
     */
    public Long getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_community.type
     *
     * @param type the value for td_community.type
     *
     * @mbggenerated Sat Mar 18 22:40:35 CST 2017
     */
    public void setType(Long type) {
        if (!ObjectUtils.equals(type, this.type)) {
            getChangeLogInfo().put("type", type);
        }
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_community.location
     *
     * @return the value of td_community.location
     *
     * @mbggenerated Sat Mar 18 22:40:35 CST 2017
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_community.location
     *
     * @param location the value for td_community.location
     *
     * @mbggenerated Sat Mar 18 22:40:35 CST 2017
     */
    public void setLocation(String location) {
        if (!ObjectUtils.equals(location, this.location)) {
            getChangeLogInfo().put("location", location);
        }
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_community.description
     *
     * @return the value of td_community.description
     *
     * @mbggenerated Sat Mar 18 22:40:35 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_community.description
     *
     * @param description the value for td_community.description
     *
     * @mbggenerated Sat Mar 18 22:40:35 CST 2017
     */
    public void setDescription(String description) {
        if (!ObjectUtils.equals(description, this.description)) {
            getChangeLogInfo().put("description", description);
        }
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_community.description_source
     *
     * @return the value of td_community.description_source
     *
     * @mbggenerated Sat Mar 18 22:40:35 CST 2017
     */
    public String getDescriptionSource() {
        return descriptionSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_community.description_source
     *
     * @param descriptionSource the value for td_community.description_source
     *
     * @mbggenerated Sat Mar 18 22:40:35 CST 2017
     */
    public void setDescriptionSource(String descriptionSource) {
        if (!ObjectUtils.equals(descriptionSource, this.descriptionSource)) {
            getChangeLogInfo().put("descriptionSource", descriptionSource);
        }
        this.descriptionSource = descriptionSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_community.add_time
     *
     * @return the value of td_community.add_time
     *
     * @mbggenerated Sat Mar 18 22:40:35 CST 2017
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_community.add_time
     *
     * @param addTime the value for td_community.add_time
     *
     * @mbggenerated Sat Mar 18 22:40:35 CST 2017
     */
    public void setAddTime(Date addTime) {
        if (!ObjectUtils.equals(addTime, this.addTime)) {
            getChangeLogInfo().put("addTime", addTime);
        }
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_community.add_user_id
     *
     * @return the value of td_community.add_user_id
     *
     * @mbggenerated Sat Mar 18 22:40:35 CST 2017
     */
    public Long getAddUserId() {
        return addUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_community.add_user_id
     *
     * @param addUserId the value for td_community.add_user_id
     *
     * @mbggenerated Sat Mar 18 22:40:35 CST 2017
     */
    public void setAddUserId(Long addUserId) {
        if (!ObjectUtils.equals(addUserId, this.addUserId)) {
            getChangeLogInfo().put("addUserId", addUserId);
        }
        this.addUserId = addUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_community.update_time
     *
     * @return the value of td_community.update_time
     *
     * @mbggenerated Sat Mar 18 22:40:35 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_community.update_time
     *
     * @param updateTime the value for td_community.update_time
     *
     * @mbggenerated Sat Mar 18 22:40:35 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        if (!ObjectUtils.equals(updateTime, this.updateTime)) {
            getChangeLogInfo().put("updateTime", updateTime);
        }
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_community.update_user_id
     *
     * @return the value of td_community.update_user_id
     *
     * @mbggenerated Sat Mar 18 22:40:35 CST 2017
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_community.update_user_id
     *
     * @param updateUserId the value for td_community.update_user_id
     *
     * @mbggenerated Sat Mar 18 22:40:35 CST 2017
     */
    public void setUpdateUserId(Long updateUserId) {
        if (!ObjectUtils.equals(updateUserId, this.updateUserId)) {
            getChangeLogInfo().put("updateUserId", updateUserId);
        }
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_community.is_deleted
     *
     * @return the value of td_community.is_deleted
     *
     * @mbggenerated Sat Mar 18 22:40:35 CST 2017
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_community.is_deleted
     *
     * @param isDeleted the value for td_community.is_deleted
     *
     * @mbggenerated Sat Mar 18 22:40:35 CST 2017
     */
    public void setIsDeleted(Boolean isDeleted) {
        if (!ObjectUtils.equals(isDeleted, this.isDeleted)) {
            getChangeLogInfo().put("isDeleted", isDeleted);
        }
        this.isDeleted = isDeleted;
    }

    @Override
    public int hashCode() {
        if ( this.hashCode == null ) {
            synchronized ( this ) {
                if ( this.hashCode == null ) {
                    Long newHashCode = null;
                    if ( getId() != null ) {
                        newHashCode = SAVED_HASHES.get( getId() );
                    }
                    
                    if ( newHashCode == null ) {
                        if ( getId() != null ) {
                            newHashCode = (long)getId().hashCode();
                        } else {
                            newHashCode = (long) super.hashCode();
                        }
                    }
                    this.hashCode = newHashCode;
                }
            }
        }
        return (int) (this.hashCode & 0xffffff);
    }

    @Override
    public boolean equals(final Object aThat) {
        
        if ( this == aThat ) {
            return true;
        }
        if( aThat == null ) {
            return false;
        }
        if (!( aThat instanceof CommunityBase )) {
            return false;
        }
        
        final CommunityBase THAT = (CommunityBase) aThat;
        boolean result = true;
        result = result && (((this.getId() == null) &&
             ( THAT.getId() == null)) || (this.getId() != null  && 
            this.getId().equals(THAT.getId())));
        return result;
    }
}