package com.henrrycheng.chyftt.intermediary.experienceComment.bo;

import com.baidu.bjf.dao.ColumnDescription;
import com.baidu.bjf.dao.FieldAccessVo;
import com.baidu.bjf.dao.Id;
import java.io.Serializable;
import java.util.Collections;
import java.util.Date;
import java.util.Map;
import java.util.WeakHashMap;
import org.apache.commons.lang.ObjectUtils;

/**
 * This bo is map to table : tb_experience_comment
 * Table description : 评论
 * @author chengyong
 */
public abstract class ExperienceCommentBase extends FieldAccessVo implements Serializable {
    /** serial Version UID. */
    private static final long serialVersionUID = -1L;

    /** hashCode temporary storage. */
    private volatile Long hashCode;

    /** Use a WeakHashMap so entries will be garbage collected once all entities 
    referring to a saved hash are garbage collected themselves. */
    private static final Map<Serializable, Long> SAVED_HASHES = 
        Collections.synchronizedMap(new WeakHashMap<Serializable, Long>());

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_experience_comment.id
     *
     * @mbggenerated Sat Mar 18 22:47:15 CST 2017
     */
    @ColumnDescription(desc = "id")
    @Id
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_experience_comment.experience_id
     *
     * @mbggenerated Sat Mar 18 22:47:15 CST 2017
     */
    @ColumnDescription(desc = "事情经过id")
    private Long experienceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_experience_comment.parent_comment_id
     *
     * @mbggenerated Sat Mar 18 22:47:15 CST 2017
     */
    @ColumnDescription(desc = "回复的评论id，不是对评论的回复时置为-1")
    private Long parentCommentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_experience_comment.content
     *
     * @mbggenerated Sat Mar 18 22:47:15 CST 2017
     */
    @ColumnDescription(desc = "内容")
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_experience_comment.count_agree
     *
     * @mbggenerated Sat Mar 18 22:47:15 CST 2017
     */
    @ColumnDescription(desc = "顶次数")
    private Long countAgree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_experience_comment.count_disagree
     *
     * @mbggenerated Sat Mar 18 22:47:15 CST 2017
     */
    @ColumnDescription(desc = "踩次数")
    private Long countDisagree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_experience_comment.add_time
     *
     * @mbggenerated Sat Mar 18 22:47:15 CST 2017
     */
    @ColumnDescription(desc = "添加时间")
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_experience_comment.add_user_id
     *
     * @mbggenerated Sat Mar 18 22:47:15 CST 2017
     */
    @ColumnDescription(desc = "添加人id")
    private Long addUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_experience_comment.update_time
     *
     * @mbggenerated Sat Mar 18 22:47:15 CST 2017
     */
    @ColumnDescription(desc = "更新时间")
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_experience_comment.update_user_id
     *
     * @mbggenerated Sat Mar 18 22:47:15 CST 2017
     */
    @ColumnDescription(desc = "更新人id")
    private Long updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_experience_comment.is_deleted
     *
     * @mbggenerated Sat Mar 18 22:47:15 CST 2017
     */
    @ColumnDescription(desc = "是否已逻辑删除，0未删除，1已删除")
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_experience_comment.id
     *
     * @return the value of tb_experience_comment.id
     *
     * @mbggenerated Sat Mar 18 22:47:15 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_experience_comment.id
     *
     * @param id the value for tb_experience_comment.id
     *
     * @mbggenerated Sat Mar 18 22:47:15 CST 2017
     */
    public void setId(Long id) {
        // If we've just been persisted and hashCode has been
        // returned then make sure other entities with this
        // ID return the already returned hash code
        if ( this.id == null && id != null && this.hashCode != null ) {
            SAVED_HASHES.put( id, this.hashCode );
        }
        if (!ObjectUtils.equals(id, this.id)) {
            getChangeLogInfo().put("id", id);
        }
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_experience_comment.experience_id
     *
     * @return the value of tb_experience_comment.experience_id
     *
     * @mbggenerated Sat Mar 18 22:47:15 CST 2017
     */
    public Long getExperienceId() {
        return experienceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_experience_comment.experience_id
     *
     * @param experienceId the value for tb_experience_comment.experience_id
     *
     * @mbggenerated Sat Mar 18 22:47:15 CST 2017
     */
    public void setExperienceId(Long experienceId) {
        if (!ObjectUtils.equals(experienceId, this.experienceId)) {
            getChangeLogInfo().put("experienceId", experienceId);
        }
        this.experienceId = experienceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_experience_comment.parent_comment_id
     *
     * @return the value of tb_experience_comment.parent_comment_id
     *
     * @mbggenerated Sat Mar 18 22:47:15 CST 2017
     */
    public Long getParentCommentId() {
        return parentCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_experience_comment.parent_comment_id
     *
     * @param parentCommentId the value for tb_experience_comment.parent_comment_id
     *
     * @mbggenerated Sat Mar 18 22:47:15 CST 2017
     */
    public void setParentCommentId(Long parentCommentId) {
        if (!ObjectUtils.equals(parentCommentId, this.parentCommentId)) {
            getChangeLogInfo().put("parentCommentId", parentCommentId);
        }
        this.parentCommentId = parentCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_experience_comment.content
     *
     * @return the value of tb_experience_comment.content
     *
     * @mbggenerated Sat Mar 18 22:47:15 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_experience_comment.content
     *
     * @param content the value for tb_experience_comment.content
     *
     * @mbggenerated Sat Mar 18 22:47:15 CST 2017
     */
    public void setContent(String content) {
        if (!ObjectUtils.equals(content, this.content)) {
            getChangeLogInfo().put("content", content);
        }
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_experience_comment.count_agree
     *
     * @return the value of tb_experience_comment.count_agree
     *
     * @mbggenerated Sat Mar 18 22:47:15 CST 2017
     */
    public Long getCountAgree() {
        return countAgree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_experience_comment.count_agree
     *
     * @param countAgree the value for tb_experience_comment.count_agree
     *
     * @mbggenerated Sat Mar 18 22:47:15 CST 2017
     */
    public void setCountAgree(Long countAgree) {
        if (!ObjectUtils.equals(countAgree, this.countAgree)) {
            getChangeLogInfo().put("countAgree", countAgree);
        }
        this.countAgree = countAgree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_experience_comment.count_disagree
     *
     * @return the value of tb_experience_comment.count_disagree
     *
     * @mbggenerated Sat Mar 18 22:47:15 CST 2017
     */
    public Long getCountDisagree() {
        return countDisagree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_experience_comment.count_disagree
     *
     * @param countDisagree the value for tb_experience_comment.count_disagree
     *
     * @mbggenerated Sat Mar 18 22:47:15 CST 2017
     */
    public void setCountDisagree(Long countDisagree) {
        if (!ObjectUtils.equals(countDisagree, this.countDisagree)) {
            getChangeLogInfo().put("countDisagree", countDisagree);
        }
        this.countDisagree = countDisagree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_experience_comment.add_time
     *
     * @return the value of tb_experience_comment.add_time
     *
     * @mbggenerated Sat Mar 18 22:47:15 CST 2017
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_experience_comment.add_time
     *
     * @param addTime the value for tb_experience_comment.add_time
     *
     * @mbggenerated Sat Mar 18 22:47:15 CST 2017
     */
    public void setAddTime(Date addTime) {
        if (!ObjectUtils.equals(addTime, this.addTime)) {
            getChangeLogInfo().put("addTime", addTime);
        }
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_experience_comment.add_user_id
     *
     * @return the value of tb_experience_comment.add_user_id
     *
     * @mbggenerated Sat Mar 18 22:47:15 CST 2017
     */
    public Long getAddUserId() {
        return addUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_experience_comment.add_user_id
     *
     * @param addUserId the value for tb_experience_comment.add_user_id
     *
     * @mbggenerated Sat Mar 18 22:47:15 CST 2017
     */
    public void setAddUserId(Long addUserId) {
        if (!ObjectUtils.equals(addUserId, this.addUserId)) {
            getChangeLogInfo().put("addUserId", addUserId);
        }
        this.addUserId = addUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_experience_comment.update_time
     *
     * @return the value of tb_experience_comment.update_time
     *
     * @mbggenerated Sat Mar 18 22:47:15 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_experience_comment.update_time
     *
     * @param updateTime the value for tb_experience_comment.update_time
     *
     * @mbggenerated Sat Mar 18 22:47:15 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        if (!ObjectUtils.equals(updateTime, this.updateTime)) {
            getChangeLogInfo().put("updateTime", updateTime);
        }
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_experience_comment.update_user_id
     *
     * @return the value of tb_experience_comment.update_user_id
     *
     * @mbggenerated Sat Mar 18 22:47:15 CST 2017
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_experience_comment.update_user_id
     *
     * @param updateUserId the value for tb_experience_comment.update_user_id
     *
     * @mbggenerated Sat Mar 18 22:47:15 CST 2017
     */
    public void setUpdateUserId(Long updateUserId) {
        if (!ObjectUtils.equals(updateUserId, this.updateUserId)) {
            getChangeLogInfo().put("updateUserId", updateUserId);
        }
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_experience_comment.is_deleted
     *
     * @return the value of tb_experience_comment.is_deleted
     *
     * @mbggenerated Sat Mar 18 22:47:15 CST 2017
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_experience_comment.is_deleted
     *
     * @param isDeleted the value for tb_experience_comment.is_deleted
     *
     * @mbggenerated Sat Mar 18 22:47:15 CST 2017
     */
    public void setIsDeleted(Boolean isDeleted) {
        if (!ObjectUtils.equals(isDeleted, this.isDeleted)) {
            getChangeLogInfo().put("isDeleted", isDeleted);
        }
        this.isDeleted = isDeleted;
    }

    @Override
    public int hashCode() {
        if ( this.hashCode == null ) {
            synchronized ( this ) {
                if ( this.hashCode == null ) {
                    Long newHashCode = null;
                    if ( getId() != null ) {
                        newHashCode = SAVED_HASHES.get( getId() );
                    }
                    
                    if ( newHashCode == null ) {
                        if ( getId() != null ) {
                            newHashCode = (long)getId().hashCode();
                        } else {
                            newHashCode = (long) super.hashCode();
                        }
                    }
                    this.hashCode = newHashCode;
                }
            }
        }
        return (int) (this.hashCode & 0xffffff);
    }

    @Override
    public boolean equals(final Object aThat) {
        
        if ( this == aThat ) {
            return true;
        }
        if( aThat == null ) {
            return false;
        }
        if (!( aThat instanceof ExperienceCommentBase )) {
            return false;
        }
        
        final ExperienceCommentBase THAT = (ExperienceCommentBase) aThat;
        boolean result = true;
        result = result && (((this.getId() == null) &&
             ( THAT.getId() == null)) || (this.getId() != null  && 
            this.getId().equals(THAT.getId())));
        return result;
    }
}