package com.henrrycheng.chyftt.intermediary.fraudMeans.bo;

import com.baidu.bjf.dao.ColumnDescription;
import com.baidu.bjf.dao.FieldAccessVo;
import com.baidu.bjf.dao.Id;
import java.io.Serializable;
import java.util.Collections;
import java.util.Date;
import java.util.Map;
import java.util.WeakHashMap;
import org.apache.commons.lang.ObjectUtils;

/**
 * This bo is map to table : td_fraud_means
 * Table description : 欺骗手段
 * @author chengyong
 */
public abstract class FraudMeansBase extends FieldAccessVo implements Serializable {
    /** serial Version UID. */
    private static final long serialVersionUID = -1L;

    /** hashCode temporary storage. */
    private volatile Long hashCode;

    /** Use a WeakHashMap so entries will be garbage collected once all entities 
    referring to a saved hash are garbage collected themselves. */
    private static final Map<Serializable, Long> SAVED_HASHES = 
        Collections.synchronizedMap(new WeakHashMap<Serializable, Long>());

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_fraud_means.id
     *
     * @mbggenerated Sat Mar 18 22:43:19 CST 2017
     */
    @ColumnDescription(desc = "id")
    @Id
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_fraud_means.name
     *
     * @mbggenerated Sat Mar 18 22:43:19 CST 2017
     */
    @ColumnDescription(desc = "手段名称")
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_fraud_means.frequency
     *
     * @mbggenerated Sat Mar 18 22:43:19 CST 2017
     */
    @ColumnDescription(desc = "使用次数")
    private Long frequency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_fraud_means.add_time
     *
     * @mbggenerated Sat Mar 18 22:43:19 CST 2017
     */
    @ColumnDescription(desc = "添加时间")
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_fraud_means.add_user_id
     *
     * @mbggenerated Sat Mar 18 22:43:19 CST 2017
     */
    @ColumnDescription(desc = "添加人id")
    private Long addUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_fraud_means.update_time
     *
     * @mbggenerated Sat Mar 18 22:43:19 CST 2017
     */
    @ColumnDescription(desc = "更新时间")
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_fraud_means.update_user_id
     *
     * @mbggenerated Sat Mar 18 22:43:19 CST 2017
     */
    @ColumnDescription(desc = "更新人id")
    private Long updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_fraud_means.is_deleted
     *
     * @mbggenerated Sat Mar 18 22:43:19 CST 2017
     */
    @ColumnDescription(desc = "是否已逻辑删除，0未删除，1已删除")
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_fraud_means.id
     *
     * @return the value of td_fraud_means.id
     *
     * @mbggenerated Sat Mar 18 22:43:19 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_fraud_means.id
     *
     * @param id the value for td_fraud_means.id
     *
     * @mbggenerated Sat Mar 18 22:43:19 CST 2017
     */
    public void setId(Long id) {
        // If we've just been persisted and hashCode has been
        // returned then make sure other entities with this
        // ID return the already returned hash code
        if ( this.id == null && id != null && this.hashCode != null ) {
            SAVED_HASHES.put( id, this.hashCode );
        }
        if (!ObjectUtils.equals(id, this.id)) {
            getChangeLogInfo().put("id", id);
        }
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_fraud_means.name
     *
     * @return the value of td_fraud_means.name
     *
     * @mbggenerated Sat Mar 18 22:43:19 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_fraud_means.name
     *
     * @param name the value for td_fraud_means.name
     *
     * @mbggenerated Sat Mar 18 22:43:19 CST 2017
     */
    public void setName(String name) {
        if (!ObjectUtils.equals(name, this.name)) {
            getChangeLogInfo().put("name", name);
        }
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_fraud_means.frequency
     *
     * @return the value of td_fraud_means.frequency
     *
     * @mbggenerated Sat Mar 18 22:43:19 CST 2017
     */
    public Long getFrequency() {
        return frequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_fraud_means.frequency
     *
     * @param frequency the value for td_fraud_means.frequency
     *
     * @mbggenerated Sat Mar 18 22:43:19 CST 2017
     */
    public void setFrequency(Long frequency) {
        if (!ObjectUtils.equals(frequency, this.frequency)) {
            getChangeLogInfo().put("frequency", frequency);
        }
        this.frequency = frequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_fraud_means.add_time
     *
     * @return the value of td_fraud_means.add_time
     *
     * @mbggenerated Sat Mar 18 22:43:19 CST 2017
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_fraud_means.add_time
     *
     * @param addTime the value for td_fraud_means.add_time
     *
     * @mbggenerated Sat Mar 18 22:43:19 CST 2017
     */
    public void setAddTime(Date addTime) {
        if (!ObjectUtils.equals(addTime, this.addTime)) {
            getChangeLogInfo().put("addTime", addTime);
        }
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_fraud_means.add_user_id
     *
     * @return the value of td_fraud_means.add_user_id
     *
     * @mbggenerated Sat Mar 18 22:43:19 CST 2017
     */
    public Long getAddUserId() {
        return addUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_fraud_means.add_user_id
     *
     * @param addUserId the value for td_fraud_means.add_user_id
     *
     * @mbggenerated Sat Mar 18 22:43:19 CST 2017
     */
    public void setAddUserId(Long addUserId) {
        if (!ObjectUtils.equals(addUserId, this.addUserId)) {
            getChangeLogInfo().put("addUserId", addUserId);
        }
        this.addUserId = addUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_fraud_means.update_time
     *
     * @return the value of td_fraud_means.update_time
     *
     * @mbggenerated Sat Mar 18 22:43:19 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_fraud_means.update_time
     *
     * @param updateTime the value for td_fraud_means.update_time
     *
     * @mbggenerated Sat Mar 18 22:43:19 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        if (!ObjectUtils.equals(updateTime, this.updateTime)) {
            getChangeLogInfo().put("updateTime", updateTime);
        }
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_fraud_means.update_user_id
     *
     * @return the value of td_fraud_means.update_user_id
     *
     * @mbggenerated Sat Mar 18 22:43:19 CST 2017
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_fraud_means.update_user_id
     *
     * @param updateUserId the value for td_fraud_means.update_user_id
     *
     * @mbggenerated Sat Mar 18 22:43:19 CST 2017
     */
    public void setUpdateUserId(Long updateUserId) {
        if (!ObjectUtils.equals(updateUserId, this.updateUserId)) {
            getChangeLogInfo().put("updateUserId", updateUserId);
        }
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_fraud_means.is_deleted
     *
     * @return the value of td_fraud_means.is_deleted
     *
     * @mbggenerated Sat Mar 18 22:43:19 CST 2017
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_fraud_means.is_deleted
     *
     * @param isDeleted the value for td_fraud_means.is_deleted
     *
     * @mbggenerated Sat Mar 18 22:43:19 CST 2017
     */
    public void setIsDeleted(Boolean isDeleted) {
        if (!ObjectUtils.equals(isDeleted, this.isDeleted)) {
            getChangeLogInfo().put("isDeleted", isDeleted);
        }
        this.isDeleted = isDeleted;
    }

    @Override
    public int hashCode() {
        if ( this.hashCode == null ) {
            synchronized ( this ) {
                if ( this.hashCode == null ) {
                    Long newHashCode = null;
                    if ( getId() != null ) {
                        newHashCode = SAVED_HASHES.get( getId() );
                    }
                    
                    if ( newHashCode == null ) {
                        if ( getId() != null ) {
                            newHashCode = (long)getId().hashCode();
                        } else {
                            newHashCode = (long) super.hashCode();
                        }
                    }
                    this.hashCode = newHashCode;
                }
            }
        }
        return (int) (this.hashCode & 0xffffff);
    }

    @Override
    public boolean equals(final Object aThat) {
        
        if ( this == aThat ) {
            return true;
        }
        if( aThat == null ) {
            return false;
        }
        if (!( aThat instanceof FraudMeansBase )) {
            return false;
        }
        
        final FraudMeansBase THAT = (FraudMeansBase) aThat;
        boolean result = true;
        result = result && (((this.getId() == null) &&
             ( THAT.getId() == null)) || (this.getId() != null  && 
            this.getId().equals(THAT.getId())));
        return result;
    }
}